{% set name = "quantum-xir" %}
{% set version = "0.2.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/XanaduAI/xir/archive/refs/tags/v{{ version }}.tar.gz
  sha256: bfc28ff386a4a742973455b61eccc574517a994bb7cfd0ea0b9e7194dae55f31

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - lark-parser >=0.11.0
    - python >=3.6

test:
  imports:
    - xir
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/XanaduAI/xir
  summary: XIR is an intermediate representation (IR) for quantum circuits.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - BastianZim
